spring:
  application:
    name: "hotel-service"

  datasource:
    url: "jdbc:postgresql://14.162.146.23:5432/hotel_service"
    username: "root"
    password: "root@2025"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
