spring:
  application:
    name: "api-gateway"
  security:
    jwt:
      secret-key: ${JWT_SECRET:b6a4f2319dbde50cf2a1e476ec9f77e3d8c22148790c4e537103c0f77e3a6c42}
      expiration: ${JWT_EXPIRATION:1209600000}

server:
  port: ${SERVER_PORT:1111}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: ${LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.route: ${LOG_LEVEL:DEBUG}
    org.springframework.cloud.loadbalancer: ${LOG_LEVEL:DEBUG}
    reactor.netty.http.client: ${LOG_LEVEL:DEBUG}